# Generated by Django 5.1.2 on 2024-10-16 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 10, 16, 16, 41, 13, 631277), null=True),
        ),
    ]
