# Generated by Django 5.1.2 on 2024-10-17 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 10, 17, 16, 7, 27, 512701), null=True),
        ),
    ]
