# Generated by Django 5.1.2 on 2024-10-17 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 10, 17, 18, 23, 54, 29605), null=True),
        ),
    ]
